name: Publish to PyPi

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      # Check if the tag matches the version in pyproject.toml
      - name: Check version matches tag
        run: |
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          TAG=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION" != "$TAG" ]; then
            echo "Tag ($TAG) does not match pyproject.toml version ($VERSION)"
            exit 1
          fi
        shell: bash

      # Build the Python package
      - name: Build the package
        run: |
          rm -rf build/ dist/ *.egg-info
          python -m build

      # Publish the package to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
